export const CATEGORIES = [
  { id: 'cards', label: 'Credit cards', short: 'Cards' },
  { id: 'loans', label: 'Loans', short: 'Loans' },
  { id: 'bank', label: 'Bank accounts', short: 'Bank' },
  { id: 'demat', label: 'Demat accounts', short: 'Demat' },
  { id: 'insurance', label: 'Insurance', short: 'Insurance' },
  { id: 'invest', label: 'Investment', short: 'Invest' },
  { id: 'deals', label: 'Deals', short: 'Deals' },
  { id: 'crypto', label: 'Crypto accounts', short: 'Crypto' },
  { id: 'games', label: 'Games', short: 'Games' },
]

// Each card shows exactly 3 facts.
export const PRODUCTS = [
  {
    id: 'axis-flipkart',
    category: 'cards',
    name: 'Axis Flipkart Credit Card',
    bank: 'Axis',
    mono: 'AX',
    color: '#97144d',
    earn: 2400,
    unit: 'per card issued',
    status: 'top',
    campaign: 'Same day payout',
    points: ['5% cashback on Flipkart & Myntra', '4 free lounge visits a year'],
    facts: [
      ['Joining fee', '₹0'],
      ['Annual fee', '₹500 + GST'],
      ['Payout in', 'Same day'],
    ],
    link: 'https://example.com/p/axis-flipkart',
  },
  {
    id: 'roarbank-upi',
    category: 'cards',
    name: 'Roarbank UPI Credit Card',
    bank: 'Unity',
    mono: 'UN',
    color: '#c99400',
    earn: 1500,
    unit: 'per card issued',
    status: 'active',
    points: ['No CIBIL or documents needed', 'Up to 20% cashback on categories'],
    facts: [
      ['Joining fee', 'Zero'],
      ['Annual fee', 'Zero'],
      ['Payout in', '3 days'],
    ],
    link: 'https://example.com/p/roarbank-upi',
  },
  {
    id: 'indusind-rupay',
    category: 'cards',
    name: 'IndusInd Platinum RuPay Card',
    bank: 'IndusInd',
    mono: 'IB',
    color: '#8b1d24',
    earn: 2100,
    unit: 'per card issued',
    status: 'top',
    points: ['Lifetime free', 'UPI payments on credit card'],
    facts: [
      ['Joining fee', '₹0'],
      ['Annual fee', '₹0'],
      ['Payout in', '7 days'],
    ],
    link: 'https://example.com/p/indusind-rupay',
  },
  {
    id: 'hdfc-millennia',
    category: 'cards',
    name: 'HDFC Millennia Credit Card',
    bank: 'HDFC',
    mono: 'HD',
    color: '#004c8f',
    earn: 2000,
    unit: 'per card issued',
    status: 'active',
    points: ['5% cashback on Amazon & Swiggy', 'Fee waived on ₹1L spend'],
    facts: [
      ['Joining fee', '₹1,000'],
      ['Annual fee', '₹1,000'],
      ['Payout in', '7 days'],
    ],
    link: 'https://example.com/p/hdfc-millennia',
  },
  {
    id: 'au-lit',
    category: 'cards',
    name: 'AU LIT Credit Card',
    bank: 'AU',
    mono: 'AU',
    color: '#e0621a',
    earn: 1800,
    unit: 'per card issued',
    status: 'active',
    points: ['Customer picks the features', 'Lifetime free'],
    facts: [
      ['Joining fee', '₹0'],
      ['Annual fee', '₹0'],
      ['Payout in', '3 days'],
    ],
    link: 'https://example.com/p/au-lit',
  },
  {
    id: 'incred-pl',
    category: 'loans',
    name: 'InCred Personal Loan',
    bank: 'InCred',
    mono: 'IN',
    color: '#e5501e',
    earn: 4,
    percent: true,
    unit: 'of loan amount',
    status: 'top',
    campaign: 'Same day payout',
    points: ['Loans up to ₹15 lakh', '100% digital process'],
    facts: [
      ['Loan up to', '₹15L'],
      ['Interest from', '16% p.a.'],
      ['Payout in', 'Same day'],
    ],
    link: 'https://example.com/p/incred-pl',
  },
  {
    id: 'ramfincorp-pl',
    category: 'loans',
    name: 'Ram Fincorp Personal Loan',
    bank: 'Ram Fincorp',
    mono: 'RF',
    color: '#0f8a9d',
    earn: 3,
    percent: true,
    unit: 'of loan amount',
    status: 'top',
    points: ['Approval within a minute', 'Salaried customers only'],
    facts: [
      ['Loan up to', '₹1L'],
      ['Interest from', '18% p.a.'],
      ['Payout in', '24 hrs'],
    ],
    link: 'https://example.com/p/ramfincorp-pl',
  },
  {
    id: 'prefr-pl',
    category: 'loans',
    name: 'Prefr Personal Loan',
    bank: 'Prefr',
    mono: 'PR',
    color: '#2f3fd6',
    earn: 2.8,
    percent: true,
    unit: 'of loan amount',
    status: 'active',
    points: ['Loans up to ₹5 lakh', 'Fully online'],
    facts: [
      ['Loan up to', '₹5L'],
      ['Interest from', '18% p.a.'],
      ['Payout in', '3 days'],
    ],
    link: 'https://example.com/p/prefr-pl',
  },

  // ---------- Bank accounts ----------
  {
    id: 'kotak-811',
    category: 'bank',
    name: 'Kotak 811 Savings Account',
    bank: 'Kotak',
    mono: 'KO',
    color: '#d71f26',
    earn: 300,
    unit: 'per account opened',
    status: 'top',
    campaign: 'Same day payout',
    points: ['Zero balance account', 'Opens by video KYC in 10 min'],
    facts: [
      ['Min. balance', '₹0'],
      ['Interest', 'Up to 4%'],
      ['Payout in', 'Same day'],
    ],
    link: 'https://example.com/p/kotak-811',
  },
  {
    id: 'idfc-savings',
    category: 'bank',
    name: 'IDFC First Savings Account',
    bank: 'IDFC First',
    mono: 'ID',
    color: '#9c1d26',
    earn: 350,
    unit: 'per account funded',
    status: 'active',
    points: ['Monthly interest credit', 'Zero fee on 28 services'],
    facts: [
      ['Min. balance', '₹10,000'],
      ['Interest', 'Up to 7%'],
      ['Payout in', '7 days'],
    ],
    link: 'https://example.com/p/idfc-savings',
  },
  {
    id: 'au-savings',
    category: 'bank',
    name: 'AU Digital Savings Account',
    bank: 'AU',
    mono: 'AU',
    color: '#e0621a',
    earn: 250,
    unit: 'per account opened',
    status: 'active',
    points: ['Fully online, no branch visit', 'Free virtual debit card'],
    facts: [
      ['Min. balance', '₹2,000'],
      ['Interest', 'Up to 7.25%'],
      ['Payout in', '3 days'],
    ],
    link: 'https://example.com/p/au-savings',
  },

  // ---------- Demat accounts ----------
  {
    id: 'angel-one',
    category: 'demat',
    name: 'Angel One Demat Account',
    bank: 'Angel One',
    mono: 'A1',
    color: '#1f5fe0',
    earn: 450,
    unit: 'per account opened',
    status: 'top',
    points: ['Free account opening', '₹0 brokerage on delivery'],
    facts: [
      ['Opening fee', '₹0'],
      ['Intraday', '₹20 / order'],
      ['Payout in', '24 hrs'],
    ],
    link: 'https://example.com/p/angel-one',
  },
  {
    id: 'upstox',
    category: 'demat',
    name: 'Upstox Demat Account',
    bank: 'Upstox',
    mono: 'UP',
    color: '#5a2d82',
    earn: 400,
    unit: 'per first trade',
    status: 'top',
    campaign: 'Bonus ₹100 this week',
    points: ['Opens in 10 minutes', 'Stocks, F&O and mutual funds'],
    facts: [
      ['Opening fee', '₹0'],
      ['Intraday', '₹20 / order'],
      ['Payout in', '24 hrs'],
    ],
    link: 'https://example.com/p/upstox',
  },
  {
    id: 'groww-demat',
    category: 'demat',
    name: 'Groww Demat Account',
    bank: 'Groww',
    mono: 'GR',
    color: '#00a37a',
    earn: 350,
    unit: 'per account opened',
    status: 'active',
    points: ['Simple app for first-timers', 'No annual charges'],
    facts: [
      ['Opening fee', '₹0'],
      ['AMC', '₹0'],
      ['Payout in', '3 days'],
    ],
    link: 'https://example.com/p/groww-demat',
  },

  // ---------- Insurance ----------
  {
    id: 'acko-car',
    category: 'insurance',
    name: 'Acko Car Insurance',
    bank: 'Acko',
    mono: 'AC',
    color: '#5f2eea',
    earn: 12,
    percent: true,
    unit: 'of premium paid',
    status: 'top',
    points: ['Policy issued instantly', 'Zero-commission direct prices'],
    facts: [
      ['Premium from', '₹2,094'],
      ['Claims settled', '96%'],
      ['Payout in', '24 hrs'],
    ],
    link: 'https://example.com/p/acko-car',
  },
  {
    id: 'care-health',
    category: 'insurance',
    name: 'Care Supreme Health Insurance',
    bank: 'Care',
    mono: 'CA',
    color: '#0d7a4d',
    earn: 15,
    percent: true,
    unit: 'of first premium',
    status: 'top',
    campaign: 'Same day payout',
    points: ['Cashless at 21,000+ hospitals', 'Unlimited cover restore'],
    facts: [
      ['Cover up to', '₹1 Cr'],
      ['Premium from', '₹650/mo'],
      ['Payout in', 'Same day'],
    ],
    link: 'https://example.com/p/care-health',
  },
  {
    id: 'hdfc-ergo-bike',
    category: 'insurance',
    name: 'HDFC Ergo Bike Insurance',
    bank: 'HDFC Ergo',
    mono: 'HE',
    color: '#c8202c',
    earn: 10,
    percent: true,
    unit: 'of premium paid',
    status: 'active',
    points: ['Renew in 2 minutes', 'No inspection needed'],
    facts: [
      ['Premium from', '₹538'],
      ['Garages', '2,000+'],
      ['Payout in', '3 days'],
    ],
    link: 'https://example.com/p/hdfc-ergo-bike',
  },

  // ---------- Investment ----------
  {
    id: 'stable-money-fd',
    category: 'invest',
    name: 'Stable Money Fixed Deposit',
    bank: 'Stable Money',
    mono: 'SM',
    color: '#0a7c5a',
    earn: 200,
    unit: 'per first FD',
    status: 'top',
    points: ['FDs up to 9.5% interest', 'Insured up to ₹5 lakh'],
    facts: [
      ['Min. amount', '₹1,000'],
      ['Returns', 'Up to 9.5%'],
      ['Lock-in', '1 year'],
    ],
    link: 'https://example.com/p/stable-money-fd',
  },
  {
    id: 'et-money-sip',
    category: 'invest',
    name: 'ET Money Mutual Fund SIP',
    bank: 'ET Money',
    mono: 'ET',
    color: '#1b8a8f',
    earn: 150,
    unit: 'per first SIP',
    status: 'active',
    points: ['Direct plans, zero commission', 'Start with ₹500 a month'],
    facts: [
      ['Min. SIP', '₹500'],
      ['Funds', '2,000+'],
      ['Fees', '₹0'],
    ],
    link: 'https://example.com/p/et-money-sip',
  },
  {
    id: 'jar-gold',
    category: 'invest',
    name: 'Jar Digital Gold Savings',
    bank: 'Jar',
    mono: 'JR',
    color: '#6b3fd4',
    earn: 50,
    unit: 'per first saving',
    status: 'active',
    points: ['Save from ₹10 a day', '24K gold, 100% secure'],
    facts: [
      ['Min. saving', '₹10'],
      ['Purity', '24K'],
      ['Withdraw', 'Anytime'],
    ],
    link: 'https://example.com/p/jar-gold',
  },

  // ---------- Deals ----------
  {
    id: 'myntra',
    category: 'deals',
    name: 'Myntra Fashion Deals',
    bank: 'Myntra',
    mono: 'MY',
    color: '#e8385f',
    earn: 6,
    percent: true,
    unit: 'of every order',
    status: 'top',
    campaign: 'Sale live',
    points: ['50–80% off top brands', 'Earn on repeat orders'],
    facts: [
      ['Min. order', '₹0'],
      ['Tracked for', '7 days'],
      ['Payout', 'Monthly'],
    ],
    link: 'https://example.com/p/myntra',
  },
  {
    id: 'ajio',
    category: 'deals',
    name: 'AJIO Deals',
    bank: 'AJIO',
    mono: 'AJ',
    color: '#2c4152',
    earn: 8,
    percent: true,
    unit: 'of every order',
    status: 'active',
    points: ['Extra 10% off for new users', 'Free delivery over ₹499'],
    facts: [
      ['Min. order', '₹0'],
      ['Tracked for', '30 days'],
      ['Payout', 'Monthly'],
    ],
    link: 'https://example.com/p/ajio',
  },
  {
    id: 'makemytrip',
    category: 'deals',
    name: 'MakeMyTrip Hotel Deals',
    bank: 'MakeMyTrip',
    mono: 'MT',
    color: '#d8262a',
    earn: 5,
    percent: true,
    unit: 'of every booking',
    status: 'active',
    points: ['Hotels, flights and buses', 'Paid after the stay'],
    facts: [
      ['Min. booking', '₹0'],
      ['Tracked for', '30 days'],
      ['Payout', 'Monthly'],
    ],
    link: 'https://example.com/p/makemytrip',
  },

  // ---------- Crypto accounts ----------
  {
    id: 'coindcx',
    category: 'crypto',
    name: 'CoinDCX Crypto Account',
    bank: 'CoinDCX',
    mono: 'CD',
    color: '#3b5cf0',
    earn: 200,
    unit: 'per KYC done',
    status: 'top',
    points: ['500+ coins to trade', 'Deposit by UPI'],
    facts: [
      ['Min. deposit', '₹100'],
      ['Trading fee', '0.5%'],
      ['Payout in', '24 hrs'],
    ],
    link: 'https://example.com/p/coindcx',
  },
  {
    id: 'mudrex',
    category: 'crypto',
    name: 'Mudrex Crypto Account',
    bank: 'Mudrex',
    mono: 'MX',
    color: '#4747d6',
    earn: 250,
    unit: 'per first deposit',
    status: 'active',
    campaign: 'Same day payout',
    points: ['Crypto SIP from ₹100', 'FIU registered'],
    facts: [
      ['Min. deposit', '₹100'],
      ['Trading fee', '0.3%'],
      ['Payout in', 'Same day'],
    ],
    link: 'https://example.com/p/mudrex',
  },
  {
    id: 'coinswitch',
    category: 'crypto',
    name: 'CoinSwitch Crypto Account',
    bank: 'CoinSwitch',
    mono: 'CS',
    color: '#1d2fb8',
    earn: 150,
    unit: 'per KYC done',
    status: 'active',
    points: ['Simple app for beginners', 'Instant INR withdrawals'],
    facts: [
      ['Min. deposit', '₹100'],
      ['Trading fee', '0.49%'],
      ['Payout in', '3 days'],
    ],
    link: 'https://example.com/p/coinswitch',
  },

  // ---------- Games ----------
  {
    id: 'ludo-king',
    category: 'games',
    name: 'Ludo King',
    bank: 'Ludo King',
    mono: 'LK',
    color: '#c99400',
    earn: 15,
    unit: 'per install',
    status: 'top',
    points: ['Install and play one game', 'Credit in 24 hrs'],
    facts: [
      ['Size', '60 MB'],
      ['Rating', '4.2 ★'],
      ['Players', '1B+'],
    ],
    link: 'https://example.com/p/ludo-king',
  },
  {
    id: 'carrom-pool',
    category: 'games',
    name: 'Carrom Pool',
    bank: 'Carrom Pool',
    mono: 'CP',
    color: '#b5541f',
    earn: 12,
    unit: 'per install',
    status: 'active',
    points: ['Install and open once', 'Works on any phone'],
    facts: [
      ['Size', '75 MB'],
      ['Rating', '4.3 ★'],
      ['Players', '100M+'],
    ],
    link: 'https://example.com/p/carrom-pool',
  },
  {
    id: 'subway-surfers',
    category: 'games',
    name: 'Subway Surfers',
    bank: 'Subway Surfers',
    mono: 'SS',
    color: '#1e7fd6',
    earn: 10,
    unit: 'per install',
    status: 'active',
    points: ['Reach level 5 to qualify', 'Credit in 48 hrs'],
    facts: [
      ['Size', '180 MB'],
      ['Rating', '4.5 ★'],
      ['Players', '1B+'],
    ],
    link: 'https://example.com/p/subway-surfers',
  },
]
